# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Formulars.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Formulars(object):
    def setupUi(self, Formulars):
        Formulars.setObjectName("Formulars")
        Formulars.resize(1280, 720)
        self.verticalLayout = QtWidgets.QVBoxLayout(Formulars)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(Formulars)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)

        self.retranslateUi(Formulars)
        QtCore.QMetaObject.connectSlotsByName(Formulars)

    def retranslateUi(self, Formulars):
        _translate = QtCore.QCoreApplication.translate
        Formulars.setWindowTitle(_translate("Formulars", "Dialog"))
        self.textBrowser.setHtml(_translate("Formulars", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,serif\'; font-size:18pt; font-weight:600;\">Дихотомия.</span><span style=\" font-size:18pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><img src=\"file:02\\clip_image002.png\" width=\"83\" height=\"44\" /><span style=\" font-size:14pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><img src=\"file:02\\clip_image004.png\" width=\"222\" height=\"40\" /><span style=\" font-size:14pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\"file:02\\clip_image006.png\" width=\"75\" height=\"44\" /><span style=\" font-size:14pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,serif\'; font-size:18pt; font-weight:600;\">Золотое Сечение.</span><span style=\" font-size:18pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\"file:02\\clip_image008.png\" width=\"146\" height=\"44\" /><span style=\" font-size:14pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\"file:02\\clip_image010.png\" width=\"164\" height=\"24\" /><span style=\" font-family:\'Times New Roman,serif\'; font-size:14pt;\">,</span><span style=\" font-size:14pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\"file:02\\clip_image012.png\" width=\"109\" height=\"44\" /><span style=\" font-size:14pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\"file:02\\clip_image014.png\" width=\"125\" height=\"24\" /><span style=\" font-family:\'Times New Roman,serif\'; font-size:14pt;\">,</span><span style=\" font-size:14pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\"file:02\\clip_image016.png\" width=\"178\" height=\"49\" /><span style=\" font-size:14pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\"file:02\\clip_image018.png\" width=\"150\" height=\"49\" /><span style=\" font-size:14pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\"file:02\\clip_image020.png\" width=\"197\" height=\"49\" /><span style=\" font-size:14pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\"file:02\\clip_image022.png\" width=\"354\" height=\"49\" /><span style=\" font-size:14pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\"file:02\\clip_image024.png\" width=\"366\" height=\"49\" /><span style=\" font-size:14pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,serif\'; font-size:14pt; font-weight:600;\"> </span><span style=\" font-size:14pt;\"> </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman,serif\'; font-size:14pt; font-weight:600;\"> </span><span style=\" font-size:14pt;\"> </span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Formulars = QtWidgets.QDialog()
    ui = Ui_Formulars()
    ui.setupUi(Formulars)
    Formulars.show()
    sys.exit(app.exec_())
